apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-util
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-util
  template:
    metadata:
      labels:
        app: ubuntu-util
    spec:
      containers:
        - name: ubuntu-util
          image: zommarin/ubuntu-util
          ports:
            - containerPort: 80
          command:
            - sleep
          args:
            - "36000"
